Update officers
cornellacsu/old_website pull request #4
Opened 2018-05-17 23:32 UTC by ef23

Adds in as many new officers for those who uploaded their picture. Also mostly jekyll-fied the officers page.

2018-05-25 00:25 UTC, dannyqiu requested changes

2018-05-25 00:25 UTC, dannyqiu commented on team.html
> +                  <!-- create a row for every 4 officers  -->
Isn't this handled by default using bootstrap's grid styling? It would automatically overflow into new rows based on the size that is set in the `col-md-<size>`.

2018-05-25 00:25 UTC, dannyqiu commented on team.html
> +                                <a href="mailto:{{ officer.email }}"><img src="img/icons/email.png" onmouseover="this.src='img/icons/email-2.png'" onmouseout="this.src='img/icons/email.png'" width="3
This should be dynamically generated/de-obfuscated to prevent email spam

2018-05-25 00:25 UTC, dannyqiu commented on _data/officers1718.json
> +         "email": ""
Should this be filled out?

2018-05-25 00:50 UTC, xinyuzhao23 commented on _data/officers1718.json
> +         "email": ""
Should what be filled out? The email? We agreed not to have emails for people other than Irene and Abrahm at one of the Ebodies.

2018-05-25 02:01 UTC, dannyqiu commented on _data/officers1718.json
> +         "email": ""
Gotcha 👍

2018-05-25 19:12 UTC, ef23 commented on team.html
> +                  <!-- create a row for every 4 officers  -->
You're right, it does. I don't think removing the row div made a difference, but I'm leaning towards keeping it because of the <br> tag after each row. I'll look into it with more detail once I'm not at the airport LOL

2018-05-25 19:12 UTC, ef23 commented on team.html
> +                                <a href="mailto:{{ officer.email }}"><img src="img/icons/email.png" onmouseover="this.src='img/icons/email-2.png'" onmouseout="this.src='img/icons/email.png'" width="3
I'm not sure what is not being dynamically generated here?

2018-05-26 01:55 UTC, dannyqiu commented on team.html
> +                                <a href="mailto:{{ officer.email }}"><img src="img/icons/email.png" onmouseover="this.src='img/icons/email-2.png'" onmouseout="this.src='img/icons/email.png'" width="3
Dynamically generated in the sense that it is rendered when the page loads. Jekyll only "compiles" the page into static html - in the end, the emails are still scrape-able in the html. 

https://stackoverflow.com/a/23195351

2018-06-01 05:02 UTC, ef23 commented on team.html
> +                                <a href="mailto:{{ officer.email }}"><img src="img/icons/email.png" onmouseover="this.src='img/icons/email-2.png'" onmouseout="this.src='img/icons/email.png'" width="3
Should be fixed now. Not the most elegant solution though, but it should protect us from scrapers decently well.

2018-06-01 05:02 UTC, ef23 commented on _data/officers1718.json
> +         "email": ""
Fixed, only Irene and Abrahm have emails now

2018-06-07 05:06 UTC, dannyqiu requested changes

2018-06-07 05:06 UTC, dannyqiu commented on team.html
> +                                      $(this).attr('href', href.replace("!", "@cornell.edu"));
I think it would be cleaner if you use the `data-` attribute and then have the javascript read from this to construct the email. This solution would cause issues for people with an `!` in their email (though why would anyone do this, but just in case)

2018-06-08 03:05 UTC, ef23 commented on team.html
> +                                      $(this).attr('href', href.replace("!", "@cornell.edu"));
Yeah that's a much better solution. Pushed a fix that hopefully is nicer.

2018-06-10 21:41 UTC, dannyqiu requested changes

2018-06-10 21:41 UTC, dannyqiu commented on team.html
> +                                    showEmail("acsuemail")
Can this be done through a selector (https://stackoverflow.com/a/7084588/3026621), and then setting the `href` attribute of anything that matches?

2018-07-26 04:33 UTC, ef23 commented on team.html
> +                                    showEmail("acsuemail")
oh man its been a while since I looked at this, but I've updated it.

2018-07-26 14:39 UTC, dannyqiu commented on team.html
> +                    {% if forloop.last == true %}
Why not put this code block outside of the for loop?

2018-07-26 14:39 UTC, dannyqiu commented on team.html
> +          <script>
?

2018-07-27 04:37 UTC, ef23 commented on team.html
> +                    {% if forloop.last == true %}
lol i forgot jekyll generates the html then the js runs, i was trying to make sure that the code block only ran after everything was generated

2018-07-27 05:04 UTC, dannyqiu commented on team.html
> +                      <
?

2018-07-27 05:28 UTC, dannyqiu approved these changes

2018-07-27 05:28 UTC, dannyqiu commented
lgtm

2018-07-27 05:31 UTC, merged